### ISSUE TITLE
mapbox-gl.css missing

### ISSUE THREAD

**Issue by serialc** [dougmccune/animated-wildfire-progression-maps#1]
The mapbox-gl.css file reference in index.hml is missing but without effect.

```js
<link rel='stylesheet' href='node_modules/mapbox-gl/dist/mapbox-gl.css' />
```

I replaced with:

```js
<link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
```

Doesn't appear to have any effect except to remove the console error or warning (if I omit the link entirely).

Nice animation!

**Comment by dougmccune** [comment]
Good catch, thanks! It's updated now
